"""Utility script to visualize inference performance from saved CSV results."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


PLOT_DIR = Path("plots")


def visualize_performance(
    ground_truth: np.ndarray, pred_plain: np.ndarray, pred_fhe: np.ndarray, output_dir: Path = PLOT_DIR
) -> None:
    """Generate comparison plots between ground truth, plain, and FHE predictions."""

    output_dir.mkdir(parents=True, exist_ok=True)

    plain_mask = ~np.isnan(pred_plain).any(axis=1)
    fhe_mask = ~np.isnan(pred_fhe).any(axis=1)

    plain_errors = np.linalg.norm(pred_plain[plain_mask] - ground_truth[plain_mask], axis=1)
    fhe_errors = np.linalg.norm(pred_fhe[fhe_mask] - ground_truth[fhe_mask], axis=1)

    # CDF of Error
    plt.figure(figsize=(8, 5))
    if plain_errors.size:
        sorted_plain = np.sort(plain_errors)
        cdf_plain = np.arange(1, sorted_plain.size + 1) / sorted_plain.size
        plt.plot(sorted_plain, cdf_plain, label="Plain", color="tab:blue")
    if fhe_errors.size:
        sorted_fhe = np.sort(fhe_errors)
        cdf_fhe = np.arange(1, sorted_fhe.size + 1) / sorted_fhe.size
        plt.plot(sorted_fhe, cdf_fhe, label="FHE", color="tab:red")
    plt.xlabel("Positioning error (meters)")
    plt.ylabel("Cumulative probability")
    plt.title("CDF of Positioning Error")
    plt.grid(True, linestyle="--", alpha=0.4)
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_dir / "error_cdf.png", dpi=150)
    plt.close()

    # 3D Error Vectors
    if fhe_mask.any():
        fig = plt.figure(figsize=(8, 6))
        ax = fig.add_subplot(111, projection="3d")
        gt_points = ground_truth[fhe_mask]
        fhe_points = pred_fhe[fhe_mask]

        ax.scatter(gt_points[:, 0], gt_points[:, 1], gt_points[:, 2], c="black", marker="x", label="Ground Truth")
        ax.scatter(
            fhe_points[:, 0],
            fhe_points[:, 1],
            fhe_points[:, 2],
            c="tab:red",
            marker="^",
            label="FHE Prediction",
        )

        for tgt, pred in zip(gt_points, fhe_points):
            ax.plot(
                [tgt[0], pred[0]],
                [tgt[1], pred[1]],
                [tgt[2], pred[2]],
                color="tab:red",
                alpha=0.5,
                linewidth=0.8,
            )

        ax.set_title("3D Error Vectors (Ground Truth to FHE)")
        ax.set_xlabel("X")
        ax.set_ylabel("Y")
        ax.set_zlabel("Z")
        ax.legend()
        plt.tight_layout()
        plt.savefig(output_dir / "error_vectors_3d.png", dpi=150)
        plt.close(fig)

    # 2D X-Y Projection
    if fhe_mask.any():
        plt.figure(figsize=(7, 6))
        gt_points = ground_truth[fhe_mask]
        fhe_points = pred_fhe[fhe_mask]
        plt.scatter(gt_points[:, 0], gt_points[:, 1], c="black", marker="x", label="Ground Truth")
        plt.scatter(fhe_points[:, 0], fhe_points[:, 1], c="tab:red", marker="^", label="FHE Prediction")
        plt.xlabel("X")
        plt.ylabel("Y")
        plt.title("X-Y Projection: Ground Truth vs FHE")
        plt.legend()
        plt.grid(True, linestyle="--", alpha=0.4)
        plt.tight_layout()
        plt.savefig(output_dir / "xy_projection.png", dpi=150)
        plt.close()


def load_results(csv_path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    data = np.genfromtxt(csv_path, delimiter=",", names=True)
    if data.ndim == 0:  # Single row becomes scalar structured array
        data = np.array([data])

    ground_truth = np.vstack((data["gt_x"], data["gt_y"], data["gt_z"]))
    pred_plain = np.vstack((data["pred_plain_x"], data["pred_plain_y"], data["pred_plain_z"]))
    pred_fhe = np.vstack((data["pred_fhe_x"], data["pred_fhe_y"], data["pred_fhe_z"]))

    return ground_truth.T, pred_plain.T, pred_fhe.T



def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize inference performance from CSV results.")
    parser.add_argument(
        "--results-csv",
        type=Path,
        default=Path("artifacts/inference_results.csv"),
        help="CSV file generated by infer_location.py containing predictions and targets.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PLOT_DIR,
        help="Directory where plots will be saved.",
    )
    return parser.parse_args()



def main() -> int:
    args = parse_args()
    if not args.results_csv.exists():
        print(f"CSV file not found at {args.results_csv}. Run infer_location.py first.")
        return 1

    ground_truth, pred_plain, pred_fhe = load_results(args.results_csv)
    visualize_performance(ground_truth, pred_plain, pred_fhe, args.output_dir)
    print(f"Saved plots to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
